name: CloudBox Enterprise CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configurar Credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init -backend-config="bucket=cloudbox-terraform-state-20245274" -backend-config="key=cloudbox-enterprise/terraform.tfstate" -backend-config="region=us-east-1" -backend-config="dynamodb_table=terraform-lock"

      - name: Import Existing Resources
        run: |
          terraform import aws_lambda_event_source_mapping.sqs_trigger c069288a-d844-4ed5-8f8b-be257a0afb25

      - name: Terraform Format
        run: terraform fmt -check -diff > fmt.log || (cat fmt.log && exit 1)

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
   